console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

#[secondary_prompt]
#  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
#  foreground = 'p:black'
#  background = 'transparent'

#[transient_prompt]
#  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
#  foreground = 'p:black'
#  background = 'transparent'

#[upgrade]
#  source = 'cdn'
#  interval = '168h'
#  auto = false
#  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]] 
    type = 'path'
    style = 'plain'
    background = 'transparent' 
    foreground = 'green'
    template = '{{ .Path }}'
   
    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'magenta'
    bacground = 'transparent'
    template = "❯"

[transient_prompt]
  foreground = "magenta"
  background = 'transparent'
  template = '❯ '


#[[tooltips]]
#  leading_diamond = ''
#  trailing_diamond = ''
#  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
#  foreground = 'p:white'
#  background = 'p:orange'
#  type = 'aws'
#  style = 'diamond'
#  tips = ['aws']

#  [tooltips.properties]
#    display_default = true

#[[tooltips]]
#  leading_diamond = ''
#  trailing_diamond = ''
#  template = '  {{ .Name }} '
#  foreground = 'p:white'
#  background = 'p:blue'
#  type = 'az'
#  style = 'diamond'
#  tips = ['az']

#  [tooltips.properties]
#    display_default = true
